@PlatformService.API_HostAddress = 
@PlatformService.API_Local_HostAddress =  http://localhost:5240
@PlatformApi = /api/platforms

GET {{PlatformService.API_Local_HostAddress}}{{PlatformApi}}

###

GET {{PlatformService.API_Local_HostAddress}}{{PlatformApi}}/5

###

POST {{PlatformService.API_Local_HostAddress}}{{PlatformApi}}
Content-Type: application/json

{
    "name": "Docker",
    "publisher": "Docker",
    "cost": "Free"
}

###
